//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSDbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOWINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHOWINFO()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.MOVIEs = new HashSet<MOVIE>();
        }
    
        public int ShowID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool isSpecificDay { get; set; }
        public string SpecificDay { get; set; }
        public Nullable<int> ReservedSeatsCount { get; set; }
        public Nullable<int> UnreservedSeatsCount { get; set; }
        public System.TimeSpan ShowTime { get; set; }
        public int MovieHallID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        public virtual MOVIEHALL MOVIEHALL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIE> MOVIEs { get; set; }
    }
}
